/*
 * SPDX-FileCopyrightText: © 2017-2026 Istari Digital, Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

// Package filter provides typed values and a parameterised expression builder
// for composing dgraph @filter clauses on generated <Entity>Query types.
//
// Generated By<Field> methods accept []UUID or []String and feed them into
// Builder.EqGroupUUID / Builder.EqGroupString. Consumers can also build
// custom expressions directly with Builder for cases the generator does not
// cover (multi-predicate joins, non-equality operators, domain defaults).
package filter

import (
	"fmt"
	"strings"
)

// UUID is one UUID-valued filter term, optionally negated. A leading "!" in
// the parsed source negates the term ("!abc" becomes {Negated: true, Value: "abc"}).
type UUID struct {
	Negated bool
	Value   string
}

// String is one string-valued filter term, optionally negated.
type String struct {
	Negated bool
	Value   string
}

// ParseUUID parses "value" or "!value" into a UUID.
func ParseUUID(s string) UUID {
	neg, v := parseNegation(s)
	return UUID{Negated: neg, Value: v}
}

// ParseString parses "value" or "!value" into a String.
func ParseString(s string) String {
	neg, v := parseNegation(s)
	return String{Negated: neg, Value: v}
}

func parseNegation(s string) (bool, string) {
	if strings.HasPrefix(s, "!") {
		return true, s[1:]
	}
	return false, s
}

// term is one predicate-agnostic value used by Builder.
type term struct {
	value   string
	negated bool
}

// Builder composes parameterised DQL @filter expressions. Terms within an
// EqGroup join with OR; groups join with AND. Required terms become their own
// single-term group. The output is the (expression, positional params) pair
// that typed.Query[T].Filter consumes.
type Builder struct {
	groups []string
	params []any
}

func (b *Builder) param(v any) string {
	b.params = append(b.params, v)
	return fmt.Sprintf("$%d", len(b.params))
}

// EqGroupUUID adds an OR-group of eq(predicate, value) terms for one
// UUID-typed predicate. An empty terms slice is a no-op.
func (b *Builder) EqGroupUUID(predicate string, terms []UUID) {
	if len(terms) == 0 {
		return
	}
	tg := make([]term, 0, len(terms))
	for _, t := range terms {
		tg = append(tg, term{value: t.Value, negated: t.Negated})
	}
	b.addEqGroup(predicate, tg)
}

// EqGroupString adds an OR-group of eq(predicate, value) terms for one
// string-typed predicate.
func (b *Builder) EqGroupString(predicate string, terms []String) {
	if len(terms) == 0 {
		return
	}
	tg := make([]term, 0, len(terms))
	for _, t := range terms {
		tg = append(tg, term{value: t.Value, negated: t.Negated})
	}
	b.addEqGroup(predicate, tg)
}

func (b *Builder) addEqGroup(predicate string, terms []term) {
	parts := make([]string, 0, len(terms))
	for _, t := range terms {
		eq := fmt.Sprintf("eq(%s, %s)", predicate, b.param(t.value))
		if t.negated {
			eq = "NOT " + eq
		}
		parts = append(parts, eq)
	}
	b.groups = append(b.groups, "("+strings.Join(parts, " OR ")+")")
}

// RequiredEq adds a single mandatory eq(predicate, value) term (its own group).
func (b *Builder) RequiredEq(predicate, value string) {
	b.groups = append(b.groups, fmt.Sprintf("eq(%s, %s)", predicate, b.param(value)))
}

// Build returns the combined DQL filter expression and its parameters. When
// no groups were added it returns ("", nil) — callers should skip the
// .Filter() call entirely in that case.
func (b *Builder) Build() (string, []any) {
	if len(b.groups) == 0 {
		return "", nil
	}
	return strings.Join(b.groups, " AND "), b.params
}
