package migrate

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// renderMigrationFile produces the generated .go source and its companion
// .schema content for one scaffolded migration. When the delta has additive
// changes, the step embeds the .schema and applies it via EnsureSchema; when the
// delta is purely flagged (retype/removal), the .schema is empty and the step is
// a stub carrying only the action-required notes — the scaffolder never emits an
// unsafe EnsureSchema. goSrc is gofmt-formatted.
func renderMigrationFile(pkg, name string, id, after int64, delta Delta) (goSrc, schema string) {
	additive := delta.HasAdditive()
	schema = strings.Join(delta.Additive(), "\n")
	if schema != "" {
		schema += "\n"
	}

	varName := varNameFor(name, id)
	schemaVar := schemaVarFor(name)
	stepName := name + "_schema"

	var b strings.Builder
	b.WriteString("// Code generated by `migrate create`; review and edit before committing.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	b.WriteString("import (\n")
	if additive {
		b.WriteString("\t_ \"embed\"\n\n")
	}
	b.WriteString("\t\"github.com/matthewmcneely/modusgraph/migrate\"\n)\n\n")

	if additive {
		fmt.Fprintf(&b, "//go:embed %d_%s.schema\n", id, name)
		fmt.Fprintf(&b, "var %s string\n\n", schemaVar)
	}

	if delta.HasFlagged() {
		b.WriteString(renderNotes(delta))
	}

	fmt.Fprintf(&b, "var %s = migrate.Migration{\n", varName)
	fmt.Fprintf(&b, "\tID:    %d,\n", id)
	if after == 0 {
		b.WriteString("\tAfter: 0, // root migration\n")
	} else {
		fmt.Fprintf(&b, "\tAfter: %d, // current head at creation\n", after)
	}
	fmt.Fprintf(&b, "\tName:  %q,\n", name)
	b.WriteString("\tSteps: []migrate.Step{\n\t\t{\n")
	fmt.Fprintf(&b, "\t\t\tName: %q,\n", stepName)
	if additive {
		fmt.Fprintf(&b, "\t\t\tSchema: migrate.SchemaChange{EnsureSchema: %s},\n", schemaVar)
		b.WriteString("\t\t\t// Down: drop these predicates to make this reversible (see MIGRATIONS.md).\n")
	} else {
		b.WriteString("\t\t\t// No additive schema generated — see SCAFFOLD NOTES above.\n")
		b.WriteString("\t\t\t// Add an Alter/RetypePredicate or data step as needed.\n")
	}
	b.WriteString("\t\t},\n")
	b.WriteString("\t\t// TODO: add data steps (backfills) here if needed.\n")
	b.WriteString("\t},\n}\n")

	if formatted, err := format.Source([]byte(b.String())); err == nil {
		return string(formatted), schema
	}
	// A formatting failure means the template itself is malformed; return the
	// raw source so the (always-run) format check in tests surfaces it loudly
	// rather than hiding a bad template behind silently-dropped output.
	return b.String(), schema
}

// renderNotes builds the SCAFFOLD NOTES comment block for the destructive or
// ambiguous changes the scaffolder refuses to emit as schema.
func renderNotes(d Delta) string {
	var b strings.Builder
	b.WriteString("// SCAFFOLD NOTES — action required, not applied automatically:\n")
	for _, t := range d.TypeChanged {
		fmt.Fprintf(&b, "//   TYPE CHANGE: %s\n", t)
		b.WriteString("//     Retype is destructive — use migrate.RetypePredicate (see MIGRATIONS.md), not EnsureSchema.\n")
	}
	for _, r := range d.Removed {
		fmt.Fprintf(&b, "//   REMOVED: %s\n", r)
		b.WriteString("//     Not auto-dropped. If intentional, add an explicit Alter drop step.\n")
	}
	b.WriteByte('\n')
	return b.String()
}

// sanitizeName lowercases a human migration name and reduces it to snake_case
// using only [a-z0-9_], collapsing runs of other characters to single
// underscores.
func sanitizeName(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var b strings.Builder
	pendingSep := false
	for _, r := range s {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			if pendingSep && b.Len() > 0 {
				b.WriteByte('_')
			}
			pendingSep = false
			b.WriteRune(r)
		default:
			pendingSep = true
		}
	}
	return b.String()
}

// lowerCamel converts snake_case to lowerCamelCase, prefixing "m" when the
// result would otherwise start with a digit (an invalid Go identifier).
func lowerCamel(snake string) string {
	parts := strings.Split(snake, "_")
	var b strings.Builder
	for i, p := range parts {
		if p == "" {
			continue
		}
		if i == 0 || b.Len() == 0 {
			b.WriteString(p)
		} else {
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	out := b.String()
	if out == "" {
		return "migration"
	}
	if out[0] >= '0' && out[0] <= '9' {
		return "m" + out
	}
	return out
}

// varNameFor is the migration variable name: lowerCamel(name) + the timestamp ID.
func varNameFor(name string, id int64) string {
	return lowerCamel(name) + strconv.FormatInt(id, 10)
}

// schemaVarFor is the embedded-schema variable name: lowerCamel(name) + "Schema".
func schemaVarFor(name string) string {
	return lowerCamel(name) + "Schema"
}
