version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gochecknoinits
    - gosec
    - govet
    - ineffassign
    - lll
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unused
  settings:
    lll:
      line-length: 120
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
