// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"
	"encoding/json"

	"github.com/matthewmcneely/modusgraph"
)

// StudioClient provides typed CRUD operations for Studio entities.
type StudioClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Studio by its UID.
func (c *StudioClient) Get(ctx context.Context, uid string) (*Studio, error) {
	// Query using the reflectable struct so dgman can project all fields.
	var proxy studioReflectable
	err := c.conn.Get(ctx, &proxy, uid)
	if err != nil {
		return nil, err
	}
	// Unmarshal back into the entity via JSON round-trip, which invokes
	// the entity's UnmarshalJSON and populates private fields.
	data, err := json.Marshal(&proxy)
	if err != nil {
		return nil, err
	}
	var result Studio
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Studio into the database.
func (c *StudioClient) Add(ctx context.Context, v *Studio) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Studio in the database. The UID field must be set.
func (c *StudioClient) Update(ctx context.Context, v *Studio) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Studio with the given UID from the database.
func (c *StudioClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// List retrieves Studio entities with optional pagination.
func (c *StudioClient) List(ctx context.Context, opts ...PageOption) ([]Studio, error) {
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	var proxies []studioReflectable
	q := c.conn.Query(ctx, studioReflectable{}).
		First(cfg.first)
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&proxies)
	if err != nil {
		return nil, err
	}
	return unmarshalStudioSlice(proxies)
}

// unmarshalStudioSlice converts reflectable proxies to entities via JSON round-trip.
func unmarshalStudioSlice(proxies []studioReflectable) ([]Studio, error) {
	data, err := json.Marshal(proxies)
	if err != nil {
		return nil, err
	}
	var results []Studio
	if err := json.Unmarshal(data, &results); err != nil {
		return nil, err
	}
	return results, nil
}
