/*
 * SPDX-FileCopyrightText: © 2017-2026 Istari Digital, Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

// Package typed binds a Go type to the otherwise any-typed modusgraph.Client,
// giving you generic, type-safe CRUD and a fluent query builder with no
// per-entity code generation. It is the handwritten substrate that
// modusgraph-gen's generated clients compose over, and it is useful on its own
// wherever you want compile-time types over modusgraph.
//
// # Why
//
// modusgraph.Client is value-oriented: its methods take and return any, and a
// query is assembled by hand from dgman primitives and decoded into a slice you
// declare at the call site. That works, but every call site repeats the same
// shape — declare the destination, build the query, decode, check the type.
// Package typed lifts that shape into the type system once.
//
// Without the typed layer, a "first matching record" lookup carries the type on
// every line and decodes by hand:
//
//	var out []Person
//	q := client.Query(ctx, &Person{}).
//		Filter("eq(name, $1)", "Alice").
//		First(1)
//	if err := q.Nodes(&out); err != nil {
//		return nil, err
//	}
//	var person *Person
//	if len(out) > 0 {
//		person = &out[0]
//	}
//
// With it, the type is declared once — when the client is constructed — and the
// terminal returns exactly what you asked for:
//
//	people := typed.NewClient[Person](client)
//	person, err := people.Query(ctx).
//		Filter("eq(name, $1)", "Alice").
//		First()
//	// person is *Person; nil when nothing matched.
//
// # The query builder
//
// Query[T] is a fluent builder. Builder methods (Filter, OrderAsc, Limit,
// WhereEdge, and the rest) return *Query[T] for chaining; terminals (Nodes,
// First, NodesAndCount, IterNodes) execute and decode typed results. The
// builder delegates the actual querying, parameter binding, and injection-safe
// $N substitution to dgman — it adds the type binding and the fragment
// composition dgman does not provide:
//
//   - Accumulated Filter fragments AND together, each fragment parenthesized so
//     a fragment containing OR keeps its precedence.
//   - OrGroup ORs several sub-scopes into one parenthesized group.
//   - WhereEdge constrains T by a predicate of a neighbouring node reached over
//     an edge, resolved by a pre-pass and intersected with any root you set.
//   - IterNodes streams arbitrarily large result sets one page at a time over a
//     single read-only snapshot.
//
// # Composing larger requests
//
// MultiQuery batches N same-type blocks into one Dgraph round-trip, keyed by
// block name. The filter subpackage builds parameterised @filter expressions
// (the substrate behind generated By<Field> and Or combinators), and the search
// subpackage merges ordered result sets by ID.
//
// # Tracing
//
// Every terminal opens a span through a process-wide tracer that is a no-op by
// default. Install one with SetTracer to emit spans without the typed package
// depending on any telemetry library.
package typed
