name: ci-go-load-tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "**/*.go"
      - "**/go.mod"
      - .github/workflows/*

permissions:
  contents: read
  actions: write

jobs:
  ci-go-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26.4
          cache-dependency-path: go.sum

      - name: Run Unit Tests
        run: BENCHMARK_DURATION=30s go test -race -v ./load_test/...
